[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Dacazh"
authors = [{name = "Qi Zhang", email = "qzhang.xmu@qq.com"}]
dynamic = ["version", "description"]